openapi: 3.0.3
info:
  title: SAR component API endpoint specification
  version: 1.0.0
  description: |
    Specification for the API endpoint which digital prison and probation products must provide to satisfy subject access
    requests. The "Subject Access Request" product will this endpoint from each service in turn. It will collate teh response
    into a single PDF file and make it available to HMPPS's SAR team a.k.a. the Branston team.
  contact:
      name: SAR Support Slack channel #ask-subject-access-requests
      url: https://moj.enterprise.slack.com/archives/C0636R18BCL
tags:
  - name: Subject Access Requests
    description: Endpoint specification
paths:
  /subject-access-request:
    get:
      summary: API call to retrieve SAR data from a product
      tags:
        - Subject Access Requests
      description: |
        Either the Prisoner Reference Number (PRN) or Case Reference Number (CRN) must be provided as part of the request.
        * If the product receiving the request uses the transmitted identifier type, it can respond with its data and HTTP code 200.
        * If the product receiving the request does not use the transmitted identifier type, it should respond with HTTP code 204.

      parameters:
        - $ref: "#/components/parameters/prisonerReferenceNumber"
        - $ref: "#/components/parameters/caseReferenceNumber"
        - $ref: "#/components/parameters/fromDate"
        - $ref: "#/components/parameters/toDate"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                additionalProperties: true
        '204':
          description: Request Successfully Processed - No content found
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
components:
  responses:
    IncorrectRequest:
      description: The request was not formed correctly
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    Unauthorised:
      description: The client does not have authorisation to make this request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
  parameters:
    prisonerReferenceNumber:
      name: prn
      description: NOMIS Prisoner Reference Number
      in: query
      schema:
        type: string
    caseReferenceNumber:
      name: crn
      description: nDelius Case Reference Number
      in: query
      schema:
        type: string
    fromDate:
      name: fromDate
      in: query
      description: Optional parameter denoting minimum date of event occurrence for which should be returned in the response
      schema:
        type: string
        format: date
    toDate:
      name: toDate
      in: query
      description: Optional parameter denoting maximum date of event occurrence for which should be returned in the response
      schema:
        type: string
        format: date
  schemas:
    errorResponse:
      properties:
        developerMessage:
          type: string
        errorCode:
          type: integer
        status:
          type: integer
        userMessage:
          type: string