openapi: 3.0.3
info:
  title: SAR component API endpoint specification
  version: 1.0.0
  description: |
    Specification for the API endpoint which digital prison and probation products must provide to satisfy subject access
    requests. The "Subject Access Request" product will call this endpoint for each service in turn. It will collate the response
    into a single PDF file and make it available to the SAR team a.k.a. the Branston team.
  contact:
      name: SAR Support Slack channel #ask-subject-access-requests
      url: https://moj.enterprise.slack.com/archives/C0636R18BCL
tags:
  - name: Subject Access Request
    description: Endpoint specification
paths:
  /subject-access-request:
    get:
      summary: API call to retrieve SAR data from a product
      tags:
        - Subject Access Request
      description: |
        Either NOMIS Prison Number (PRN) or nDelius Case Reference Number (CRN) must be provided as part of the request.
        * If the product uses the identifier type transmitted in the request, it can respond with its data and HTTP code 200.
        * If the product uses the identifier type transmitted in the request but has no data to respond with, it should respond with HTTP code 204
        * If the product does not use the identifier type transmitted in the request, it should respond with HTTP code 209.

      parameters:
        - $ref: "#/components/parameters/prisonReferenceNumber"
        - $ref: "#/components/parameters/caseReferenceNumber"
        - $ref: "#/components/parameters/fromDate"
        - $ref: "#/components/parameters/toDate"
      responses:
        '200':
          $ref: '#/components/responses/ContentFound'
        '204':
          description: Request successfully processed - no content found
        '209':
          description: Subject Identifier is not recognised by this service
        '400':
          $ref: '#/components/responses/IncorrectRequest'
        '401':
          $ref: '#/components/responses/Unauthorised'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  responses:
    ContentFound:
      description: Request successfully processed - content found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/successResponse'
    IncorrectRequest:
      description: The request was not formed correctly
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    Unauthorised:
      description: The client does not have authorisation to make this request due to a missing/invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    Forbidden:
      description: The client does not have authorisation to make this request due to insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
  parameters:
    prisonReferenceNumber:
      name: prn
      description: NOMIS Prison Reference Number
      in: query
      schema:
        type: string
    caseReferenceNumber:
      name: crn
      description: nDelius Case Reference Number
      in: query
      schema:
        type: string
    fromDate:
      name: fromDate
      in: query
      description: Optional parameter denoting minimum date of event occurrence which should be returned in the response
      schema:
        type: string
        format: date
    toDate:
      name: toDate
      in: query
      description: Optional parameter denoting maximum date of event occurrence which should be returned in the response
      schema:
        type: string
        format: date
  schemas:
    successResponse:
      properties:
        content:
          type: object
          additionalProperties: true
    errorResponse:
      properties:
        developerMessage:
          type: string
        errorCode:
          type: integer
        status:
          type: integer
        userMessage:
          type: string
